---
language: ruby
bundler_args: --without system_tests
script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'
before_install:
  - gem install bundler # -v x.x.x if a specific version is needed
matrix:
  fast_finish: true
  include:
  - sudo: required
    services: docker
    rvm: '2.3.3'
    env: PUPPET_INSTALL_VERSION="1.10.8" PUPPET_INSTALL_TYPE=agent BEAKER_set="centos-7-docker"
    script: bundle exec rake acceptance
    bundler_args: --without development
  - sudo: required
    services: docker
    rvm: '2.3.3'
    env: PUPPET_INSTALL_VERSION="1.10.8" PUPPET_INSTALL_TYPE=agent BEAKER_set="debian-8-docker"
    script: bundle exec rake acceptance
    bundler_args: --without development
  - sudo: required
    services: docker
    rvm: '2.3.3'
    env: PUPPET_INSTALL_VERSION="1.10.8" PUPPET_INSTALL_TYPE=agent BEAKER_set="ubuntu-1604-docker"
    script: bundle exec rake acceptance
    bundler_args: --without development
